"""The decorated band: the six version points of methylamine on the (tau, eta) cylinder form a trigonal antiprism
whose symmetry group, inside the symmetries of the cylinder, has order 12 and is isomorphic to G12 = <b, t, u>.

Checks (exact, finite):
  1. G12, modelled as (permutation of 1..5, star sign), has order 12 and the element-order profile of D6 = S3 x C2
     (orders 1, 2, 3, 6 with multiplicities 1, 7, 2, 2).
  2. G12 acts faithfully on the six cosets G12/H, H = <b>, so its image on the six version points is all of G12.
  3. The stabiliser of the six points {(0,+), (2pi/3,+), (4pi/3,+), (pi,-), (5pi/3,-), (pi/3,-)} in the finite group
     of cylinder symmetries generated by rotations by multiples of pi/3, the reflection tau -> -tau and the flip
     eta -> -eta (order 24) has order 12, and its element-order profile is again (1, 7, 2, 2): no extra symmetry.
"""
import itertools, sys
from fractions import Fraction

# ---- 1, 2: the group G12 on five labels with a star sign
def compose(a, b):  # (a*b)(x) = a(b(x)); star signs multiply
    return (tuple(a[0][b[0][i]] for i in range(5)), a[1]*b[1])
E = ((0,1,2,3,4), 1)
b = ((0,2,1,4,3), -1)      # (23)(45)*
t = ((1,2,0,3,4), 1)       # (123)
u = ((0,1,2,4,3), 1)       # (45)
G = {E}; frontier=[E]
while frontier:
    g=frontier.pop(); 
    for h in (b,t,u):
        k=compose(g,h)
        if k not in G: G.add(k); frontier.append(k)
def order(g):
    k=1; x=g
    while x!=E: x=compose(x,g); k+=1
    return k
prof={}
for g in G: prof[order(g)]=prof.get(order(g),0)+1
ok = len(G)==12 and prof=={1:1,2:7,3:2,6:2}
print('G12: order', len(G), 'element orders', dict(sorted(prof.items())), 'D6 profile' if ok else 'MISMATCH')
H={E,b}
cosets=[]
for g in G:
    c=frozenset(compose(g,h) for h in H)
    if c not in cosets: cosets.append(c)
assert len(cosets)==6
def act(g): return tuple(cosets.index(frozenset(compose(g,x) for x in c)) for c in cosets)
images={act(g) for g in G}
ok2 = len(images)==12
print('action on the six versions: faithful' if ok2 else 'action NOT faithful', '(', len(images), 'distinct permutations )')

# ---- 3: the pattern on the cylinder; tau in units of pi/3 mod 6, eta = +-1
pts={(0,1),(2,1),(4,1),(3,-1),(5,-1),(1,-1)}
def sym(k, refl, flip):
    def f(p):
        tau,eta=p
        if refl: tau=-tau
        tau=(tau+k)%6
        if flip: eta=-eta
        return (tau,eta)
    return f
syms=[(k,r,fl) for k in range(6) for r in (0,1) for fl in (0,1)]
stab=[s for s in syms if {sym(*s)(p) for p in pts}==pts]
def compose_sym(a, c):  # a after c, as functions
    fa, fc = sym(*a), sym(*c)
    # find the symmetry equal to fa∘fc by matching on three generic points
    probe=[(0,1),(1,1),(2,-1)]
    target=[fa(fc(p)) for p in probe]
    for s in syms:
        if [sym(*s)(p) for p in probe]==target: return s
    raise RuntimeError
ident=(0,0,0)
def sorder(s):
    k=1; x=s
    while x!=ident: x=compose_sym(x,s); k+=1
    return k
sprof={}
for s in stab: sprof[sorder(s)]=sprof.get(sorder(s),0)+1
ok3 = len(stab)==12 and sprof=={1:1,2:7,3:2,6:2}
print('pattern stabiliser on the cylinder: order', len(stab), 'element orders', dict(sorted(sprof.items())), 'D6 profile' if ok3 else 'MISMATCH')
if not (ok and ok2 and ok3): sys.exit('verify_antiprism: mismatch')
print('verify_antiprism: all checks pass')
